import { Box } from "@chakra-ui/react"
import Hero from "../Hero"
import Head from "next/head"
import ContactInfo from "../ContactInfo"

const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box pt="20vh" maxW={["335px", "350px"]} m="0 auto">
        <Hero />
        <ContactInfo />
        {children}
      </Box>
    </>
  )
}

export default MainLayout
